surah_name_to_number_en = {
    'al-fatiha': 1,           # Al-Fatiha
    'al-baqara': 2,           # Al-Baqara
    'al-imran': 3,            # Al-Imran
    'an-nisa': 4,             # An-Nisa
    'al-maida': 5,            # Al-Maida
    'al-anam': 6,             # Al-An'am
    'al-araf': 7,             # Al-A'raf
    'al-anfal': 8,            # Al-Anfal
    'at-tawba': 9,            # At-Tawba
    'yunus': 10,              # Yunus
    'hud': 11,                # Hud
    'yusuf': 12,              # Yusuf
    'ar-rad': 13,             # Ar-Ra'd
    'ibrahim': 14,            # Ibrahim
    'al-hijr': 15,            # Al-Hijr
    'an-nahl': 16,            # An-Nahl
    'al-isra': 17,            # Al-Isra
    'al-kahf': 18,            # Al-Kahf
    'maryam': 19,             # Maryam
    'ta-ha': 20,              # Ta-Ha
    'al-anbiya': 21,          # Al-Anbiya
    'al-hajj': 22,            # Al-Hajj
    'al-muminun': 23,         # Al-Mu'minun
    'an-nur': 24,             # An-Nur
    'al-furqan': 25,          # Al-Furqan
    'ash-shuara': 26,         # Ash-Shu'ara
    'an-naml': 27,            # An-Naml
    'al-qasas': 28,           # Al-Qasas
    'al-ankabut': 29,         # Al-Ankabut
    'ar-rum': 30,             # Ar-Rum
    'luqman': 31,             # Luqman
    'as-sajda': 32,           # As-Sajda
    'al-ahzab': 33,           # Al-Ahzab
    'saba': 34,               # Saba
    'fatir': 35,              # Fatir
    'ya-sin': 36,             # Ya-Sin
    'as-saffat': 37,          # As-Saffat
    'sad': 38,                # Sad
    'az-zumar': 39,           # Az-Zumar
    'ghafir': 40,             # Ghafir
    'fusilat': 41,            # Fussilat
    'ash-shura': 42,          # Ash-Shura
    'az-zukhruf': 43,         # Az-Zukhruf
    'ad-dukhan': 44,          # Ad-Dukhan
    'al-jathiya': 45,         # Al-Jathiya
    'al-ahqaf': 46,           # Al-Ahqaf
    'muhammad': 47,           # Muhammad
    'al-fath': 48,            # Al-Fath
    'al-hujurat': 49,         # Al-Hujurat
    'qaf': 50,                # Qaf
    'az-zariyat': 51,         # Az-Zariyat
    'at-tur': 52,             # At-Tur
    'an-najm': 53,            # An-Najm
    'al-qamar': 54,           # Al-Qamar
    'ar-rahman': 55,          # Ar-Rahman
    'al-waqia': 56,           # Al-Waqi'a
    'al-hadid': 57,           # Al-Hadid
    'al-mujadila': 58,        # Al-Mujadila
    'al-hashr': 59,           # Al-Hashr
    'al-mumtahina': 60,       # Al-Mumtahina
    'as-saff': 61,            # As-Saff
    'al-jumuah': 62,          # Al-Jumu'ah
    'al-munafiqun': 63,       # Al-Munafiqun
    'at-taghabun': 64,        # At-Taghabun
    'at-talaq': 65,           # At-Talaq
    'at-tahrim': 66,          # At-Tahrim
    'al-mulk': 67,            # Al-Mulk
    'al-qalam': 68,           # Al-Qalam
    'al-haqqa': 69,           # Al-Haqqa
    'al-maarij': 70,          # Al-Ma'arij
    'nuh': 71,                # Nuh
    'al-jinn': 72,            # Al-Jinn
    'al-muzzammil': 73,       # Al-Muzzammil
    'al-muddathir': 74,       # Al-Muddathir
    'al-qiyama': 75,          # Al-Qiyama
    'al-insan': 76,           # Al-Insan
    'al-mursalat': 77,        # Al-Mursalat
    'an-naba': 78,            # An-Naba
    'an-naziat': 79,          # An-Nazi'at
    'abasa': 80,              # Abasa
    'at-takwir': 81,          # At-Takwir
    'al-infitar': 82,         # Al-Infitar
    'al-mutaffifin': 83,      # Al-Mutaffifin
    'al-inshiqaq': 84,        # Al-Inshiqaq
    'al-buruj': 85,           # Al-Buruj
    'at-tariq': 86,           # At-Tariq
    'al-ala': 87,             # Al-A'la
    'al-ghashiya': 88,        # Al-Ghashiya
    'al-fajr': 89,            # Al-Fajr
    'al-balad': 90,           # Al-Balad
    'ash-shams': 91,          # Ash-Shams
    'al-layl': 92,            # Al-Layl
    'ad-duha': 93,            # Ad-Duha
    'ash-sharh': 94,          # Ash-Sharh
    'at-tin': 95,             # At-Tin
    'al-alaq': 96,            # Al-Alaq
    'al-qadr': 97,            # Al-Qadr
    'al-bayyina': 98,         # Al-Bayyina
    'az-zalzala': 99,         # Az-Zalzalah
    'al-adiyat': 100,         # Al-Adiyat
    'al-qaria': 101,          # Al-Qari'a
    'at-takathur': 102,       # At-Takathur
    'al-asr': 103,            # Al-Asr
    'al-humazah': 104,        # Al-Humazah
    'al-fil': 105,            # Al-Fil
    'quraish': 106,           # Quraish
    'al-maun': 107,           # Al-Ma'un
    'al-kawthar': 108,        # Al-Kawthar
    'al-kafirun': 109,        # Al-Kafirun
    'an-nasr': 110,           # An-Nasr
    'al-masad': 111,          # Al-Masad
    'al-ikhlas': 112,         # Al-Ikhlas
    'al-falaq': 113,          # Al-Falaq
    'an-nas': 114,            # An-Nas
}

surah_name_to_number_uz = {
    'fotiha': 1,              # Al-Fatiha
    'baqara': 2,              # Al-Baqara
    'imron': 3,               # Al-Imran
    'niso': 4,                # An-Nisa
    'maida': 5,               # Al-Maida
    'anam': 6,                # Al-An'am
    'arof': 7,                # Al-A'raf
    'anfal': 8,               # Al-Anfal
    'tavba': 9,               # At-Tawba
    'yunus': 10,              # Yunus
    'hud': 11,                # Hud
    'yusuf': 12,              # Yusuf
    'rad': 13,                # Ar-Ra'd
    'ibrohim': 14,            # Ibrahim
    'hijr': 15,               # Al-Hijr
    'nahl': 16,               # An-Nahl
    'isro': 17,               # Al-Isra
    'kahf': 18,               # Al-Kahf
    'maryam': 19,             # Maryam
    'taha': 20,               # Ta-Ha
    'anbiyo': 21,             # Al-Anbiya
    'haj': 22,                # Al-Hajj
    'muminun': 23,            # Al-Mu'minun
    'nur': 24,                # An-Nur
    'furqon': 25,             # Al-Furqan
    'shuaro': 26,             # Ash-Shu'ara
    'naml': 27,               # An-Naml
    'qasas': 28,              # Al-Qasas
    'ankabut': 29,            # Al-Ankabut
    'rum': 30,                # Ar-Rum
    'luqmon': 31,             # Luqman
    'sajda': 32,              # As-Sajda
    'ahzob': 33,              # Al-Ahzab
    'saba': 34,               # Saba
    'fotir': 35,              # Fatir
    'yasin': 36,              # Ya-Sin
    'saffat': 37,             # As-Saffat
    'sod': 38,                # Sad
    'az-zumar': 39,           # Az-Zumar
    'gofir': 40,              # Ghafir
    'fusilat': 41,            # Fussilat
    'shuro': 42,              # Ash-Shura
    'zuxruf': 43,             # Az-Zukhruf
    'duxon': 44,              # Ad-Dukhan
    'al-jathiya': 45,         # Al-Jathiya
    'al-ahqaf': 46,           # Al-Ahqaf
    'muhammad': 47,           # Muhammad
    'fath': 48,               # Al-Fath
    'al-hujurat': 49,         # Al-Hujurat
    'qaf': 50,                # Qaf
    'az-zariyat': 51,         # Az-Zariyat
    'tur': 52,                # At-Tur
    'najm': 53,               # An-Najm
    'qamar': 54,              # Al-Qamar
    'rahmon': 55,             # Ar-Rahman
    'voqea': 56,              # Al-Waqi'a
    'al-hadid': 57,           # Al-Hadid
    'al-mujadila': 58,        # Al-Mujadila
    'al-hashr': 59,           # Al-Hashr
    'al-mumtahina': 60,       # Al-Mumtahina
    'as-saff': 61,            # As-Saff
    'al-jumuah': 62,          # Al-Jumu'ah
    'al-munafiqun': 63,       # Al-Munafiqun
    'at-taghabun': 64,        # At-Taghabun
    'at-talaq': 65,           # At-Talaq
    'tahrim': 66,             # At-Tahrim
    'mulk': 67,               # Al-Mulk
    'qalam': 68,              # Al-Qalam
    'haqqa': 69,              # Al-Haqqa
    'maorij': 70,             # Al-Ma'arij
    'nuh': 71,                # Nuh
    'jin': 72,                # Al-Jinn
    'muzzammil': 73,          # Al-Muzzammil
    'muddassir': 74,          # Al-Muddathir
    'qiyomat': 75,            # Al-Qiyama
    'inson': 76,              # Al-Insan
    'mursalot': 77,           # Al-Mursalat
    'naba': 78,               # An-Naba
    'noziot': 79,             # An-Nazi'at
    'abasa': 80,              # Abasa
    'takvir': 81,             # At-Takwir
    'infitor': 82,            # Al-Infitar
    'mutaffifin': 83,         # Al-Mutaffifin
    'inshiqoq': 84,           # Al-Inshiqaq
    'al-buruj': 85,           # Al-Buruj
    'at-tariq': 86,           # At-Tariq
    'alo': 87,                # Al-A'la
    'goshiya': 88,            # Al-Ghashiya
    'fajr': 89,               # Al-Fajr
    'balad': 90,              # Al-Balad
    'shams': 91,              # Ash-Shams
    'layl': 92,               # Al-Layl
    'zuho': 93,               # Ad-Duha
    'inshirox': 94,           # Ash-Sharh
    'tin': 95,                # At-Tin
    'al-alaq': 96,            # Al-Alaq
    'qadr': 97,               # Al-Qadr
    'al-bayyina': 98,         # Al-Bayyina
    'az-zalzala': 99,         # Az-Zalzalah
    'al-adiyat': 100,         # Al-Adiyat
    'al-qaria': 101,          # Al-Qari'a
    'at-takathur': 102,       # At-Takathur
    'asr': 103,               # Al-Asr
    'al-humazah': 104,        # Al-Humazah
    'fil': 105,               # Al-Fil
    'quraysh': 106,           # Quraish
    'al-maun': 107,           # Al-Ma'un
    'kavsar': 108,            # Al-Kawthar
    'al-kafirun': 109,        # Al-Kafirun
    'an-nasr': 110,           # An-Nasr
    'al-masad': 111,          # Al-Masad
    'ixlos': 112,             # Al-Ikhlas
    'falaq': 113,             # Al-Falaq
    'an-nos': 114,            # An-Nas
}


def resolve_surah(name: str) -> int | None:
    """Map an English or Uzbek surah name to its 1-114 number.

    Case-insensitive; tolerates surrounding whitespace and a trailing
    ``-oyat`` that users sometimes append.
    """
    key = name.strip().lower().removesuffix("-oyat").strip()
    return surah_name_to_number_en.get(key) or surah_name_to_number_uz.get(key)
