surah_name_to_number_en = {
                    'al-fatiha': 1,           # Al-Fatiha
                    'al-baqara': 2,           # Al-Baqara
                    'al-imran': 3,            # Al-Imran
                    'an-nisa': 4,             # An-Nisa
                    'al-maida': 5,            # Al-Maida
                    'al-anam': 6,             # Al-An'am
                    'al-araf': 7,             # Al-A'raf
                    'al-anfal': 8,            # Al-Anfal
                    'at-tawba': 9,            # At-Tawba
                    'yunus': 10,              # Yunus
                    'hud': 11,                # Hud
                    'yusuf': 12,              # Yusuf
                    'ibrahim': 13,            # Ibrahim
                    'al-hijr': 14,            # Al-Hijr
                    'an-nahl': 15,            # An-Nahl
                    'al-isra': 17,            # Al-Isra
                    'al-kahf': 18,            # Al-Kahf
                    'maryam': 19,             # Maryam
                    'ta-ha': 20,              # Ta-Ha
                    'al-anbiya': 21,          # Al-Anbiya
                    'al-hajj': 22,            # Al-Hajj
                    'al-muminun': 23,         # Al-Mu'minun
                    'al-furqan': 25,          # Al-Furqan
                    'an-naml': 27,            # An-Naml
                    'al-ankabut': 29,         # Al-Ankabut
                    'ar-rum': 30,             # Ar-Rum
                    'luqman': 31,             # Luqman
                    'as-sajda': 32,           # As-Sajda
                    'al-ahzab': 33,           # Al-Ahzab
                    'ya-sin': 36,             # Ya-Sin
                    'az-zumar': 39,           # Az-Zumar
                    'fusilat': 41,            # Fussilat
                    'al-jathiya': 45,         # Al-Jathiya
                    'al-ahqaf': 46,           # Al-Ahqaf
                    'muhammad': 47,           # Muhammad
                    'al-fath': 48,            # Al-Fath
                    'al-hujurat': 49,         # Al-Hujurat
                    'qaf': 50,                # Qaf
                    'az-zariyat': 51,         # Az-Zariyat
                    'al-hadid': 57,           # Al-Hadid
                    'al-mujadila': 58,        # Al-Mujadila
                    'al-hashr': 59,           # Al-Hashr
                    'al-mumtahina': 60,       # Al-Mumtahina
                    'as-saff': 61,            # As-Saff
                    'al-jumuah': 62,          # Al-Jumu'ah
                    'al-munafiqun': 63,       # Al-Munafiqun
                    'at-taghabun': 64,        # At-Taghabun
                    'at-talaq': 65,           # At-Talaq
                    'al-buruj': 85,           # Al-Buruj
                    'at-tariq': 86,           # At-Tariq
                    'al-alaq': 96,            # Al-Alaq
                    'al-qadr': 97,            # Al-Qadr
                    'al-bayyina': 98,         # Al-Bayyina
                    'az-zalzala': 99,         # Az-Zalzalah
                    'al-adiyat': 100,         # Al-Adiyat
                    'al-qaria': 101,          # Al-Qari'a
                    'at-takathur': 102,       # At-Takathur
                    'al-asr': 103,            # Al-Asr
                    'al-humazah': 104,        # Al-Humazah
                    'al-fil': 105,            # Al-Fil
                    'quraish': 106,           # Quraish
                    'al-maun': 107,           # Al-Ma'un
                    'al-kawthar': 108,        # Al-Kawthar
                    'al-kafirun': 109,        # Al-Kafirun
                    'an-nasr': 110,           # An-Nasr
                    'al-masad': 111,          # Al-Masad
                    'al-ikhlas': 112,         # Al-Ikhlas
                    'al-falaq': 113,          # Al-Falaq
                    'an-nas': 114,            # An-Nas
                }
surah_name_to_number_uz = {
                    'fotiha': 1,           # Al-Fatiha
                    'baqara': 2,           # Al-Baqara
                    'imron': 3,            # Al-Imran
                    'niso': 4,             # An-Nisa
                    'maida': 5,            # Al-Maida
                    'anam': 6,             # Al-An'am
                    'arof': 7,             # Al-A'raf
                    'anfal': 8,            # Al-Anfal
                    'tavba': 9,            # At-Tawba
                    'yunus': 10,              # Yunus
                    'hud': 11,                # Hud
                    'yusuf': 12,              # Yusuf
                    'ibrohim': 13,            # Ibrahim
                    'hijr': 14,            # Al-Hijr
                    'nahl': 15,            # An-Nahl
                    'isro': 17,            # Al-Isra
                    'kahf': 18,            # Al-Kahf
                    'maryam': 19,             # Maryam
                    'taha': 20,              # Ta-Ha
                    'anbiyo': 21,          # Al-Anbiya
                    'haj': 22,            # Al-Hajj
                    'muminun': 23,         # Al-Mu'minun
                    'furqon': 25,          # Al-Furqan
                    'naml': 27,            # An-Naml
                    'ankabut': 29,         # Al-Ankabut
                    'rum': 30,             # Ar-Rum
                    'luqmon': 31,             # Luqman
                    'sajda': 32,           # As-Sajda
                    'ahzob': 33,           # Al-Ahzab
                    'yasin': 36,             # Ya-Sin
                    'az-zumar': 39,           # Az-Zumar
                    'fusilat': 41,            # Fussilat
                    'al-jathiya': 45,         # Al-Jathiya
                    'al-ahqaf': 46,           # Al-Ahqaf
                    'muhammad': 47,           # Muhammad
                    'fath': 48,            # Al-Fath
                    'al-hujurat': 49,         # Al-Hujurat
                    'qaf': 50,                # Qaf
                    'az-zariyat': 51,         # Az-Zariyat
                    'al-hadid': 57,           # Al-Hadid
                    'al-mujadila': 58,        # Al-Mujadila
                    'al-hashr': 59,           # Al-Hashr
                    'al-mumtahina': 60,       # Al-Mumtahina
                    'as-saff': 61,            # As-Saff
                    'al-jumuah': 62,          # Al-Jumu'ah
                    'al-munafiqun': 63,       # Al-Munafiqun
                    'at-taghabun': 64,        # At-Taghabun
                    'at-talaq': 65,           # At-Talaq
                    'al-buruj': 85,           # Al-Buruj
                    'at-tariq': 86,           # At-Tariq
                    'al-alaq': 96,            # Al-Alaq
                    'qadr': 97,            # Al-Qadr
                    'al-bayyina': 98,         # Al-Bayyina
                    'az-zalzala': 99,         # Az-Zalzalah
                    'al-adiyat': 100,         # Al-Adiyat
                    'al-qaria': 101,          # Al-Qari'a
                    'at-takathur': 102,       # At-Takathur
                    'asr': 103,            # Al-Asr
                    'al-humazah': 104,        # Al-Humazah
                    'fil': 105,            # Al-Fil
                    'quraysh': 106,           # Quraish
                    'al-maun': 107,           # Al-Ma'un
                    'kavsar': 108,        # Al-Kawthar
                    'al-kafirun': 109,        # Al-Kafirun
                    'an-nasr': 110,           # An-Nasr
                    'al-masad': 111,          # Al-Masad
                    'ixlos': 112,         # Al-Ikhlas
                    'falaq': 113,          # Al-Falaq
                    'an-nos': 114,            # An-Nas
                }
          